# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  apt_packages:
    - librrd-dev
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv 0.6.12
      - asdf global uv 0.6.12
    create_environment:
      - uv venv
    install:
      - uv sync
    build:
      html:
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
