"""Store data on the model for reporting and sending to RRDtool.

Revision ID: 4e7e77981e5f
Revises: ef493389b3c9
Create Date: 2021-07-23 19:53:06.841889

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4e7e77981e5f"
down_revision = "ef493389b3c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column("node", sa.Column("up_time_seconds", sa.Integer(), nullable=True))
    op.add_column("node", sa.Column("link_count", sa.Integer(), nullable=True))
    op.add_column("node", sa.Column("radio_link_count", sa.Integer(), nullable=True))
    op.add_column("node", sa.Column("dtd_link_count", sa.Integer(), nullable=True))
    op.add_column("node", sa.Column("tunnel_link_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column("node", "tunnel_link_count")
    op.drop_column("node", "dtd_link_count")
    op.drop_column("node", "radio_link_count")
    op.drop_column("node", "link_count")
    op.drop_column("node", "up_time_seconds")
    # ### end Alembic commands ###
