"""Migrations found after SQLAlchemy 2.0 update.

Also dropped PostgreSQL support.

Revision ID: 9ee59d3b14f9
Revises: 43142bd50852
Create Date: 2024-09-06 13:21:14.372403

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9ee59d3b14f9"
down_revision = "43142bd50852"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "link",
        "type",
        existing_type=sa.VARCHAR(length=7),
        type_=sa.Enum(
            "DTD",
            "WIREGUARD",
            "TUN",
            "RF",
            "UNKNOWN",
            name="linktype",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column("link", "olsr_cost", existing_type=sa.FLOAT(), nullable=False)
    op.alter_column(
        "node",
        "band",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.Enum(
            "900MHz",
            "2GHz",
            "3GHz",
            "5GHz",
            "Unknown",
            "",
            name="band",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "node_error",
        "details",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "node_error",
        "details",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "node",
        "band",
        existing_type=sa.Enum(
            "900MHz",
            "2GHz",
            "3GHz",
            "5GHz",
            "Unknown",
            "",
            name="band",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=25),
        existing_nullable=False,
    )
    op.alter_column("link", "olsr_cost", existing_type=sa.FLOAT(), nullable=True)
    op.alter_column(
        "link",
        "type",
        existing_type=sa.Enum(
            "DTD",
            "WIREGUARD",
            "TUN",
            "RF",
            "UNKNOWN",
            name="linktype",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=7),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
