"""Added some unique indexes to the 'node' table.

Revision ID: c0ea1eda0604
Revises: f176fea49e85
Create Date: 2020-12-17 20:11:09.130170

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c0ea1eda0604"
down_revision = "f176fea49e85"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "active_ip",
        "node",
        ["wlan_ip"],
        unique=True,
        postgres_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_index(
        "active_mac",
        "node",
        ["wlan_mac_address"],
        unique=True,
        postgres_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_index(
        "active_name",
        "node",
        ["name"],
        unique=True,
        postgres_where=sa.text("status = 'ACTIVE'"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("active_name", table_name="node")
    op.drop_index("active_mac", table_name="node")
    op.drop_index("active_ip", table_name="node")
    # ### end Alembic commands ###
