"""Add table to store collector statistics.

Revision ID: ef493389b3c9
Revises: 522b1ff95551
Create Date: 2021-03-29 14:18:44.086937

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ef493389b3c9"
down_revision = "522b1ff95551"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collector_stat",
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("finished_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("link_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("polling_duration", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("total_duration", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column(
            "other_stats", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("started_at", name=op.f("pk_collector_stat")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collector_stat")
    # ### end Alembic commands ###
